
export const elements = [
        { data: { id: '1', label: 'Input URL',io: "1" }},
        { data: { id: '2', label: 'Features', io: "2" }},
        { data: { id: '3', label: 'Protocol' }},
        { data: { id: '4', label: 'Number of @s in hostname' }},
        { data: { id: '5', label: 'Number of // in path' }},
        { data: { id: '6', label: 'Number of / in path' }},
        { data: { id: '7', label: 'Random characters' }},
        { data: { id: '8', label: 'URL length'}},
        { data: { id: '9', label: 'Number of - in hostname' }},
        { data: { id: '10', label: 'Existence of shady top level domain' }},
        { data: { id: '11', label: 'Existence of ip address in host name' }},
        { data: { id: '12', label: 'Number of third level domains' }},
        { data: { id: '13', label: 'Length of query components' }},
        { data: { id: '14', label: 'Length of hostname' }},
        { data: { id: '15', label: 'Y/N', io: "1" }},
        { data: { source: '1', target: '2'} },
        { data: { source: '2', target: '3'} },
        { data: { source: '2', target: '4'} },
        { data: { source: '2', target: '5'} },
        { data: { source: '2', target: '6'} },
        { data: { source: '2', target: '7'} },
        { data: { source: '2', target: '8'} },
        { data: { source: '2', target: '9'} },
        { data: { source: '2', target: '10'} },
        { data: { source: '2', target: '11'} },
        { data: { source: '2', target: '12'} },
        { data: { source: '2', target: '13'} },
        { data: { source: '2', target: '14'} },
        { data: { source: '3', target: '15'} },
        { data: { source: '4', target: '15'} },
        { data: { source: '5', target: '15'} },
        { data: { source: '6', target: '15'} },
        { data: { source: '7', target: '15'} },
        { data: { source: '8', target: '15'} },
        { data: { source: '9', target: '15'} },
        { data: { source: '10', target: '15'} },
        { data: { source: '11', target: '15'} },
        { data: { source: '12', target: '15'} },
        { data: { source: '13', target: '15'} },
        { data: { source: '14', target: '15'} },
     ];
  
   